definitions:
  models.ResponseError:
    properties:
      error: {}
    type: object
info:
  contact: {}
paths:
  /get_list_category:
    get:
      consumes:
      - application/json
      description: API for creating on demand order
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      security:
      - ApiKeyAuth: []
      summary: Create On Demand Order
      tags:
      - order
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
